server:
  port: 83

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      dynamic:
          ssm:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://localhost:3306/system?serverTimezone=Asia/Shanghai&characterEncoding=utf8
              username: root
              password: 123456
          ssj:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://localhost:3306/server?serverTimezone=Asia/Shanghai&characterEncoding=utf8
              username: root
              password: 123456
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

      # 连接池配置
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      pool-prepared-statements: true
      max-open-prepared-statements: 20

      #在空闲连接回收器线程运行期间休眠的时间值,以毫秒为单位，一般比minEvictableIdleTimeMillis小
      time-between-eviction-runs-millis: 60000
      #连接池中连接，在时间段内一直空闲，被逐出连接池的时间(1000*60*60)，以毫秒为单位
      min-evictable-idle-time-millis: 300000

      # 连接有效性检测
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
