server:
  port: 83

spring:
  datasource:
    druid:
      db1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://pro:3306/system?serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: root
        password: 123456

      db2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://pro:3306/server?serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: root
        password: 123456


